
const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

const exercises = [
  { "name": "Yoga Push Up", "video_url": "https://www.youtube.com/watch?v=Iqq_RTiYDi4" },
  { "name": "Waiters Squat", "video_url": "https://www.youtube.com/watch?v=JWglpiX0EAQ" },
  { "name": "Upper Nerve Flossing", "video_url": "https://www.youtube.com/watch?v=axG9_hUbk-s" },
  { "name": "Two Arm Overhead Hold", "video_url": "https://www.youtube.com/watch?v=rtIq413ppoA" },
  { "name": "Two Arm Overhead Carry", "video_url": "https://www.youtube.com/watch?v=A-ECJK-GvzM" },
  { "name": "Two Arm Front Rack Carry", "video_url": "https://www.youtube.com/watch?v=chnb83Ot2H4" },
  { "name": "Two Arm Farmer Carry", "video_url": "https://www.youtube.com/watch?v=CRpXSABd72o" },
  { "name": "Turkish Sit Up", "video_url": "https://www.youtube.com/watch?v=8AuYEHKdDrk" },
  { "name": "Thoracic Extension Rotation", "video_url": "https://www.youtube.com/watch?v=GuDMNfmycZ0" },
  { "name": "Supinated Bar Hang", "video_url": "https://www.youtube.com/watch?v=cvPj5lYlBWo" },
  { "name": "Sumo Stance Good Morning", "video_url": "https://www.youtube.com/watch?v=BrAD_Xk1FDU" },
  { "name": "Sumo Inchworm", "video_url": "https://www.youtube.com/watch?v=ChSZkioPFMU" },
  { "name": "Sumo Inchworm With Push Up", "video_url": "https://www.youtube.com/watch?v=UMffwYHpoAg" },
  { "name": "Suitcase Deadlift", "video_url": "https://www.youtube.com/watch?v=i4XvDVP_jME" },
  { "name": "Strict Toes To Bar", "video_url": "https://www.youtube.com/watch?v=-3evQ8JE7Bw" },
  { "name": "Strict Pull Ups", "video_url": "https://www.youtube.com/watch?v=3tFZ1f5iln8" },
  { "name": "Staggered Stance Good Morning", "video_url": "https://www.youtube.com/watch?v=tsUJtT04XEQ" },
  { "name": "Squat Rotations", "video_url": "https://www.youtube.com/watch?v=xI53osM2MaM" },
  { "name": "Squat Press Out", "video_url": "https://www.youtube.com/watch?v=gz7rfvw0wG8" },
  { "name": "Squat Pass Throughs", "video_url": "https://www.youtube.com/watch?v=1GAQs3ywanY" },
  { "name": "Single Leg Box Hamstring Curls", "video_url": "https://www.youtube.com/watch?v=plVNiqGqnmU" },
  { "name": "Side Shuffles", "video_url": "https://www.youtube.com/watch?v=HoPAmmAW_rg" },
  { "name": "Side Plank", "video_url": "https://www.youtube.com/watch?v=DOfeGjJBFiM" },
  { "name": "Shoulder Taps", "video_url": "https://www.youtube.com/watch?v=TCLqbtNKGec" },
  { "name": "Shoulder Press", "video_url": "https://www.youtube.com/watch?v=VDjVNAtxf7s" },
  { "name": "Romanian Deadlift", "video_url": "https://www.youtube.com/watch?v=P-mt6Hu05YI" },
  { "name": "Straight Leg Row", "video_url": "https://www.youtube.com/watch?v=tb9GhAjCTXA" },
  { "name": "Sumo Deadlift", "video_url": "https://www.youtube.com/watch?v=ITf59KduEqw" },
  { "name": "Inchworm", "video_url": "https://www.youtube.com/watch?v=nCleKxj7Nds" },
  { "name": "Internal Rotation Lift Off", "video_url": "https://www.youtube.com/watch?v=2zbJ0u7Sbio" },
  { "name": "Internal Rotation Stretch", "video_url": "https://www.youtube.com/watch?v=nY3xnAaMyKk" },
  { "name": "L Hang", "video_url": "https://www.youtube.com/watch?v=LS91j8iwW_E" },
  { "name": "Lateral Banded Hip Mobility", "video_url": "https://www.youtube.com/watch?v=9n3Sbc08DsU" },
  { "name": "Lateral Box Step Ups", "video_url": "https://www.youtube.com/watch?v=8fdmWO2EaDQ" },
  { "name": "Leg Abducted Rocking", "video_url": "https://www.youtube.com/watch?v=-eJYALv-ylw" },
  { "name": "Muscle Snatch", "video_url": "https://www.youtube.com/watch?v=Z4gZ_DczTvE" },
  { "name": "One Arm Farmer Carry", "video_url": "https://www.youtube.com/watch?v=S4fobiYhvGA" },
  { "name": "One Arm High Pull", "video_url": "https://www.youtube.com/watch?v=FnZRsR2flTs" },
  { "name": "One Arm Muscle Snatch", "video_url": "https://www.youtube.com/watch?v=AdqT98KCfGE" },
  { "name": "One Arm Overhead Carry + Thruster", "video_url": "https://www.youtube.com/watch?v=Rju3VrBeFiM" },
  { "name": "One Arm Overhead Carry", "video_url": "https://www.youtube.com/watch?v=C3x9_-kbK2A" },
  { "name": "One Arm Power Row", "video_url": "https://www.youtube.com/watch?v=ImO6bmsqDTc" },
  { "name": "One Arm RKB Swings", "video_url": "https://www.youtube.com/watch?v=RPSySLmoqmY" },
  { "name": "One Arm Row", "video_url": "https://www.youtube.com/watch?v=M5YE05gncbE" },
  { "name": "One Arm Shoulder Press", "video_url": "https://www.youtube.com/watch?v=mQbBYrkFxHY" },
  { "name": "One Arm Thruster", "video_url": "https://www.youtube.com/watch?v=BuUQTmaMj3U" },
  { "name": "PVC Pass Throughs", "video_url": "https://www.youtube.com/watch?v=JqgVhMnfzpY" },
  { "name": "Paused Back Squat", "video_url": "https://www.youtube.com/watch?v=mGmUTv-srZk" },
  { "name": "Piriformis Stretch", "video_url": "https://www.youtube.com/watch?v=U5QUdsoWV9c" },
  { "name": "Pigeon Stretch", "video_url": "https://www.youtube.com/watch?v=X00JKpps_sc" },
  { "name": "Plank On Elbows", "video_url": "https://www.youtube.com/watch?v=O5JjEVloG_c" },
  { "name": "Plank On Rings", "video_url": "https://www.youtube.com/watch?v=0l7nUJXLtpQ" },
  { "name": "Prayer Stretch", "video_url": "https://www.youtube.com/watch?v=Q53qAIFGryk" },
  { "name": "Push Up T's", "video_url": "https://www.youtube.com/watch?v=VSOxo3D-SJ4" },
  { "name": "Quad Roll", "video_url": "https://www.youtube.com/watch?v=STiKThadMSI" },
  { "name": "Reverse Lunges", "video_url": "https://www.youtube.com/watch?v=4Ulc-rfmfyU" },
  { "name": "Ring Row", "video_url": "https://www.youtube.com/watch?v=hiJ7sBiA46A" },
  { "name": "RKB Swings", "video_url": "https://www.youtube.com/watch?v=_C40Gg8wO08" },
  { "name": "Groiners", "video_url": "https://www.youtube.com/watch?v=1AYdqb9FTpA" },
  { "name": "Front Rack Box Step Ups", "video_url": "https://www.youtube.com/watch?v=F06fhyrbxFE" },
  { "name": "Front Banded Hip Mobility", "video_url": "https://www.youtube.com/watch?v=Uw8qIg2vIks" },
  { "name": "Eccentric Knee Flexion", "video_url": "https://www.youtube.com/watch?v=G6sOIyUKKHw" },
  { "name": "Double KB Overhead Carry + Push Press", "video_url": "https://www.youtube.com/watch?v=qef0vghvHgE" },
  { "name": "Double KB Front Squat", "video_url": "https://www.youtube.com/watch?v=9CtH_yRCyvA" },
  { "name": "Double KB Front Rack Hold", "video_url": "https://www.youtube.com/watch?v=T29tvCpjUwo" },
  { "name": "Cuban Press", "video_url": "https://www.youtube.com/watch?v=0BSwVIj4m4k" },
  { "name": "Cuban Press Complex", "video_url": "https://www.youtube.com/watch?v=EFXPacBWTTc" },
  { "name": "Crossed Prayer", "video_url": "https://www.youtube.com/watch?v=NoVXI8kgys8" },
  { "name": "Cat Cow", "video_url": "https://www.youtube.com/watch?v=S48bK06ZzdM" },
  { "name": "Box Squats", "video_url": "https://www.youtube.com/watch?v=EFonlZyq44A" },
  { "name": "Box Pigeon Stretch", "video_url": "https://www.youtube.com/watch?v=DAxJVg0VfY0" },
  { "name": "Box Hip External Rotation Stretch", "video_url": "https://www.youtube.com/watch?v=UXtEBYxNmMA" },
  { "name": "Box Hamstring Curls", "video_url": "https://www.youtube.com/watch?v=LJfgHakCcEk" },
  { "name": "Bike", "video_url": "https://www.youtube.com/watch?v=74QVMVk0w9U" },
  { "name": "Bent Knee Bar Hang", "video_url": "https://www.youtube.com/watch?v=c35zSj8pAm0" },
  { "name": "Behind The Neck Press", "video_url": "https://www.youtube.com/watch?v=DiitwhXgwJE" },
  { "name": "Banded Side Step Overs", "video_url": "https://www.youtube.com/watch?v=khCvsfnScvU" },
  { "name": "Banded Posterior Hip Distraction", "video_url": "https://www.youtube.com/watch?v=CggfIgaahrw" },
  { "name": "Internal Hip Rotations", "video_url": "https://www.youtube.com/watch?v=FtZdAlV6lRw" },
  { "name": "Horizontal GHD Hold", "video_url": "https://www.youtube.com/watch?v=B9J8MOKBH8c" },
  { "name": "Hip IR Lift Off and Hover", "video_url": "https://www.youtube.com/watch?v=abhdZjIn29w" },
  { "name": "Hip Flexion Lift Off", "video_url": "https://www.youtube.com/watch?v=5srJfv8yiYU" },
  { "name": "Hip Airplane", "video_url": "https://www.youtube.com/watch?v=ft_V0ycZrLA" },
  { "name": "Heel Walk", "video_url": "https://www.youtube.com/watch?v=8YtBzzWOKV8" },
  { "name": "Heavy Slow Resistance Calf Raises", "video_url": "https://www.youtube.com/watch?v=1viVCoaX174" },
  { "name": "Hip Internal Rotation Lift Off", "video_url": "https://www.youtube.com/watch?v=Ky0-LCmBsws" },
  { "name": "Kneeling Halos", "video_url": "https://www.youtube.com/watch?v=bPx93lAIwec" },
  { "name": "Calf Stretch On Wall", "video_url": "https://www.youtube.com/watch?v=Yxur7u6Pxx8" },
  { "name": "Bottom Of Burpee", "video_url": "https://www.youtube.com/watch?v=uzalKwzQ22o" },
  { "name": "Bird Dog", "video_url": "https://www.youtube.com/watch?v=DnOT4pQunGc" },
  { "name": "Bent Knee Hollow Body Hold", "video_url": "https://www.youtube.com/watch?v=DUecGZ1OY5M" },
  { "name": "Curtsy Squat", "video_url": "https://www.youtube.com/watch?v=9f8wTm3_enE" },
  { "name": "Curl Up", "video_url": "https://www.youtube.com/watch?v=pDqDVrkab3E" },
  { "name": "Cross Body KB Clean", "video_url": "https://www.youtube.com/watch?v=DPAsnoW-6FE" },
  { "name": "Dynamic Quad Wall Stretch", "video_url": "https://www.youtube.com/watch?v=WvOPvwbtYzU" },
  { "name": "Double KB Single Leg Deadlift", "video_url": "https://www.youtube.com/watch?v=p0HamfaDvtQ" },
  { "name": "Half Kneeling KB Hip Opener", "video_url": "https://www.youtube.com/watch?v=Afty7GOHrrk" },
  { "name": "Glute Roll", "video_url": "https://www.youtube.com/watch?v=sXM4v_fb1og" },
  { "name": "Glute Bridge", "video_url": "https://www.youtube.com/watch?v=v1ZxMi0BTnU" },
  { "name": "GHD Hip Extensions", "video_url": "https://www.youtube.com/watch?v=7wLk_rM4e48" }
];

async function run() {
  for (const ex of exercises) {
    const { data: existing } = await supabase.from('exercises').select('id').eq('name', ex.name).single();
    if (existing) {
      await supabase.from('exercises').update({ video_url: ex.video_url }).eq('id', existing.id);
    } else {
      await supabase.from('exercises').insert({ name: ex.name, video_url: ex.video_url, category: 'mobility' });
    }
  }
  console.log("Done first 100");
}

run();
